object CheckCommand "netgear" {
    command = [ PluginDir + "/check-netgear" ]
    arguments = {
        "-base-url" = {
            value = "$netgear_base_url$"
            description = "Netgear base URL"
        }
        "-username" = {
            value = "$netgear_username$"
            description = "Username for authentication"
            required = true
        }
        "-password" = {
            value = "$netgear_password$"
            description = "Password for authentication"
            required = true
        }

        "-cpu-warning" = {
            value = "$netgear_cpu_warning$"
            description = "CPU usage warning threshold (default 50)"
        }
        "-cpu-critical" = {
            value = "$netgear_cpu_critical$"
            description = "CPU usage critical threshold (default 90)"
        }
        "-mem-warning" = {
            value = "$netgear_mem_warning$"
            description = "RAM usage warning threshold (default 50)"
        }
        "-mem-critical" = {
            value = "$netgear_mem_critical$"
            description = "RAM usage critical threshold (default 90)"
        }

        "-temp-warning" = {
            value = "$netgear_temp_warning$"
            description = "Temperature warning threshold (default 50)"
        }
        "-temp-critical" = {
            value = "$netgear_temp_critical$"
            description = "Temperature critical threshold (default 70)"
        }
        "-fan-warning" = {
            value = "$netgear_fan_warning$"
            description = "Fan speed warning threshold (default 3000)"
        }
        "-fan-critical" = {
            value = "$netgear_fan_critical$"
            description = "Fan speed critical threshold (default 5000)"
        }

        "-stats-warning" = {
            value = "$netgear_port_warning$"
            description = "Port stats warning threshold (default 5)"
        }
        "-stats-critical" = {
            value = "$netgear_port_critical$"
            description = "Port stats critical threshold (default 20)"
        }

        "-mode" = {
            value = "$netgear_mode$"
            description = "Output modes to enable {basic|ports|poe|all} (repeatable) (default: basic)"
            repeat_key = true
        }

        "-port" = {
            value = "$netgear_ports$"
            description = "Ports to check (repeatable) (default 1,2,3,4,5,6,7,8)"
            repeat_key = true
        }

        "-noperfdata" = {
            set_if = "$netgear_noperfdata$"
            description = "Do not output performance data"
        }
        "-nocpu" = {
            set_if = "$netgear_hide_cpu$"
            description = "Hide the CPU info"
        }
        "-nomem" = {
            set_if = "$netgear_hide_mem$"
            description = "Hide the RAM info"
        }
        "-notemp" = {
            set_if = "$netgear_hide_temp$"
            description = "Hide the Temperature info"
        }
        "-nofans" = {
            set_if = "$netgear_hide_fans$"
            description = "Hide the Fans info"
        }
    }
}
